version: "3.8"

services:
  # Backend
  smartbrain_back-end:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smartbrain_back-end
    environment:
      POSTGRES_URI: postgres://postgres:secretpass@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    ports:
      - "30000:3000"
    volumes:
      - ./:/usr/src/smartbrain_back-end

  # Postgres
  postgres:
    build: ./postgres
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres

  # Redis
  redis:
    image: redis
    ports:
      - "63790:6379"